title: Hayden Poore # your name (or website title) here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p> Currently pursuing an Information Science Major with  a Business Analytics Minor at the University of Colorado Boulder.
  Skilled at creating useful information from data using computational, statistical and design tools.
  
  </p>
  <a href="https://www.linkedin.com/in/hayden-poore/">LinkedIn</a> 
  <br>
  <a href="https://medium.com/@haydenpoore"/>Medium</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
